# Cấu hình Mosquitto cho Development Local
# CẢNH BÁO: Không dùng cấu hình allow_anonymous=true cho Production thực tế ngoài Internet.

# Chấp nhận kết nối không cần user/password ở môi trường dev
allow_anonymous true

# Lắng nghe các kết nối trên cổng 1883
listener 1883 0.0.0.0

# Nơi lưu trữ dữ liệu
persistence true
persistence_location /mosquitto/data/

# Log
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
